name: Training Image Build

on:
  push:
    branches:
      - main
    paths:
      - 'environments/inference/**'
      - 'environments/processing/**'
      - 'environments/training/**'
      - 'mlops/steps/**'
      - 'movie_detector/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set executable permission for the script
      run: chmod +x ./environments/training/build.sh

    - name: Run the build script from processing folder
      run: ./build.sh
      working-directory: ./environments/training
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}